import 'package:flutter/material.dart';

import 'package:enforcea/bottomMenu.dart';
import 'package:searchable_dropdown/searchable_dropdown.dart';

class TaxTools extends StatefulWidget {
  const TaxTools({Key key}) : super(key: key);

  @override
  _TaxToolsState createState() => _TaxToolsState();
}

class _TaxToolsState extends State<TaxTools> {
  String _valJasa;
  String _valJenisPPH = " ";
  String _valKapKjs = " ";
  String _valTarifBerNPWP = " ";
  String _valTarifTidakBerNPWP = " ";

  List _uraian = [
    "Dividen (non WP OP DN)",
    "Bunga (tidak termasuk bunga simpanan koperasi ke OP)",
    "Royalti",
    "Hadiah dan penghargaan ",
    "Sewa dan Penghasilan lain sehubungan dengan penggunaan harta (tidak termasuk sewa tanah/bangunan)",
    "Jasa Teknik",
    "Jasa Manajemen",
    "Jasa Konsultan",
    "Jasa Penilai (appraisal)",
    "Jasa Aktuaris",
    "Jasa Akuntansi, pembukuan, dan atestasi laporan keuangan",
    "Jasa Hukum",
    "Jasa Arsitektur",
    "Jasa Perencanaan kota dan arsitektur landscape ",
    "Jasa Perancang (design)",
    "Jasa Pengeboran (drilling) di bidang penambangan minyak dan gas bumi (migas) kecuali yang dilakukan oleh Badan Usaha Tetap (BUT)",
    "Jasa Penunjang di bidang usaha panas bumi dan penambangan minyak dan gas bumi (migas)",
    "Jasa Penambangan dan jasa penunjang di bidang usaha panas bumi dan penambangan minyak dan gas bumi (migas)",
    "Jasa Penunjang di bidang penerbangan dan bandar udara",
    "Jasa Penebangan hutan",
    "Jasa Pengolahan limbah",
    "Jasa Penyedia tenaga kerja dan/atau tenaga ahli (outsourcing services)",
    "Jasa Perantara dan/atau keagenan",
    "Jasa Bidang perdagangan surat-surat berharga, kecuali yang dilakukan Bursa Efek, Kustodian Sentral Efek Indonesia (KSEI) dan Kliring Penjaminan Efek Indonesia (KPEI)",
    "Jasa Kustodian/penyimpanan/penitipan, kecuali yang dilakukan oleh KSEI",
    "Jasa Pengisian suara (dubbing) dan/atau sulih suara",
    "Jasa Mixing film",
    "Jasa Pembuatan sarana promosi film, iklan, poster, foto, slide, klise, banner, pamphlet, baliho dan folder",
    "Jasa sehubungan dengan software atau hardware atau sistem komputer, termasuk perawatan, pemeliharaan dan perbaikan.",
    "Jasa Pembuatan dan/atau pengelolaan website",
    "Jasa Internet termasuk sambungannya",
    "Jasa Penyimpanan, pengolahan dan/atau penyaluran data, informasi, dan/atau program",
    "Jasa Instalasi/pemasangan mesin, peralatan, listrik, telepon, air, gas, AC dan/atau TV Kabel, selain yang dilakukan oleh Wajib Pajak yang ruang lingkupnya di bidang konstruksi dan mempunyai izin dan/atau sertifikasi sebagai pengusaha konstruksi ",
    "Jasa Perawatan/perbaikan/pemeliharaan mesin, peralatan, listrik, telepon, air, gas, AC dan/atau TV kabel, selain yang dilakukan oleh Wajib Pajak yang ruang lingkupnya di bidang konstruksi dan mempunyai izin dan/atau sertifikasi sebagai pengusaha konstruksi",
    "Jasa Perawatan kendaraan dan/atau alat transportasi darat.",
    "Jasa Maklon",
    "Jasa Penyelidikan dan keamanan",
    "Jasa Penyelenggara kegiatan atau event organizer",
    "Jasa Penyediaan tempat dan/atau waktu dalam media massa, media luar ruang atau media lain untuk penyampaian informasi, dan/atau jasa periklanan",
    "Jasa Pembasmian hama",
    "Jasa Kebersihan atau cleaning service",
    "Jasa Sedot septic tank",
    "Jasa Pemeliharaan kolam",
    "Jasa Katering atau tata boga",
    "Jasa Freight forwarding",
    "Jasa Logistik",
    "Jasa Pengurusan dokumen",
    "Jasa Pengepakan",
    "Jasa Loading dan unloading",
    "Jasa Laboratorium dan/atau pengujian kecuali yang dilakukan oleh lembaga atau institusi pendidikan dalam rangka penelitian akademis",
    "Jasa Pengelolaan parkir",
    "Jasa Penyondiran tanah",
    "Jasa Penyiapan dan/atau pengolahan lahan",
    "Jasa Pembibitan dan/atau penanaman bibit",
    "Jasa Pemeliharaan tanaman",
    "Jasa Permanenan",
    "Jasa Pengolahan hasil pertanian, perkebunan, perikanan, peternakan dan/atau perhutanan",
    "Jasa Dekorasi",
    "Jasa Pencetakan/penerbitan",
    "Jasa Penerjemahan",
    "Jasa Pengangkutan/ekspedisi kecuali yang telah diatur dalam Pasal 15 Undang-Undang Pajak Penghasilan",
    "Jasa Pelayanan pelabuhan",
    "Jasa Pengangkutan melalui jalur pipa",
    "Jasa Pengelolaan penitipan anak",
    "Jasa Pelatihan dan/atau kursus",
    "Jasa Pengiriman dan pengisian uang ke ATM",
    "Jasa Sertifikasi",
    "Jasa Survey",
    "Jasa Tester",
    "Jasa selain jasa-jasa tersebut di atas yang pembayarannya dibebankan pada APBN (Anggaran Pendapatan dan Belanja Negara) atau APBD (Anggaran Pendapatan dan Belanja Daerah).",
    "Dividen",
    "Bunga",
    "Royalti",
    "Sewa dan Penghasilan lain sehubungan dengan penggunaan harta",
    "Imbalan sehubungan dengan jasa pekerjaan dan kegiatan",
    "Hadiah dan penghargaan ",
    "Pensiun dan pembayaran berkala",
    "Premi swap dan transaksi lindung nilai",
    "Keuntungan karena pembebasan utang",
    "Penjualan harta di Indonesia",
    "Premi asuransi/reasuransi",
    "Penghasilan dari pengalihan saham",
    "Penghasilan Kena Pajak BUT setelah pajak",
    "Bunga Deposito ditempatkan di Dalam Negeri",
    "Bunga Deposito diempatkan di Luar Negeri",
    "Diskonto Sertifikat Bank Indonesia",
    "Jasa Giro",
    "Penjualan saham di bursa efek (saham pendiri)",
    "Penjualan salam di bursa efek (bukan saham pendiri)",
    "Bunga Diskonto Obligasi WP Dalam Negeri dan Bentuk Usaha Tetap",
    "Bunga Diskonto Obligasi WP Luar Negeri selain Bentuk Usaha Tetap",
    "Hadiah Undian",
    "Persewaan Tanah dan/atau Bangunan",
    "Perencanaan konstruksi yang berkualifikasi usaha ",
    "Perencanaan konstruksi yang tidak berkualifikasi usaha ",
    "Pelaksana konstruksi yang berkualifikasi usaha kecil",
    "Pelaksana konstruksi yang berkualifikasi usaha besar & menengah",
    "Pelaksana konstruksi yang tidak berkualifikasi usaha",
    "Pengawasan konstruksi yang berkualifikasi usaha ",
    "Pengawasan konstruksi yang tidak berkualifikasi usaha ",
    "Pengalihan harta berupa tanah dan/atau bangunan",
    "Pengalihan harta berupa tanah dan/atau bangunan & usaha real estate atas Rumah Sederhana dan Rusun Sederhana",
    "Pengalihan harta berupa tanah dan/atau bangunan kepada pemerintah",
    "Bunga Simpanan yang Dibayarkan oleh Koperasi kepada Anggota Wajib Pajak Orang Pribadi",
    "Dividen yang Diterima/Diperoleh Wajib Pajak Orang Pribadi Dalam Negeri",
    "Penghasilan Dari Usaha yang Diterima atau Diperoleh Wajib Pajak yang Memiliki Peredaran Bruto Tertentu",
    "Imbalan yang Dibayarkan/Terutang kepada Perusahaan Pelayaran Dalam Negeri",
    "Imbalan yang Diterima/Diperoleh Sehubungan dengan Pengangkutan Orang dan/atau Barang Termasuk Penyewaan Kapal Laut oleh Perusahaan Pelayaran Dalam Negeri",
    "Imbalan Charter Kapal Laut dan/atau Pesawat Udara yang Dibayarkan/Terutang Kepada Perusahaan Pelayaran dan/atau Penerbangan Luar Negeri",
    "Imbalan yang Diterima/Diperoleh Sehubungan dengan Pengangkutan Orang dan/atau Barang Termasuk Charter Kapal Laut dan/atau Pesawat Udara Oleh Perusahaan Pelayaran dan/atau Penerbangan Luar Negeri",
    "Imbalan Charter Pesawat Udara Yang Dibayarkan/Terutang Kepada Perusahaan Penerbangan Dalam Negeri",
    "Penghasilan Perwakilan Dagang Luar Negeri",
    "Kerja sama bentuk BOT (Build Operate Transfer) atau bentuk perjanjian kerja sama Bangun Guna Serah",
    "Badan Usaha Industri/Eksportir Semen",
    "Badan Usaha Industri/ eksportir Kertas",
    "Badan Usaha Industri/Eksportir Baja",
    "Badan Usaha Industri/Eksportir Otomotif",
    "Badan Usaha Industri/Eksportir Farmasi",
    "Badan Usaha/Eksportir Sektor perhutanan, perkebunan, pertanian, dan perikanan",
    "Barang Mewah Rumah, Apartemen, Kondominium, dan sejenisnya",
    "Barang Mewah Pesawat terbang dan helikopter pribadi",
    "Barang Mewah Kapal pesiar, yacht, dan sejenisnya",
    "Barang Mewah Kendaraan bermotor roda empat",
    "Barang Mewah Kendaraan bermotor roda dua dan tiga",
    "Pembelian Barang Oleh Bendaharawan/Badan Tertentu Yang Ditunjuk",
    "Impor dengan API",
    "Impor Non API",
    "Hasil Lelang (Ditjen Bea dan Cukai)",
    "Bahan Bakar Minyak/BBM SPBU/Agent/Penyalur (Final)",
    "Bahan Bakar Minyak/BBM Pihak lain (Tidak Final)",
    "Bahan Bakar Gas",
    "Pelumas",
  ];

  List _jenisPPH = [
    "PPh23",
    "PPh23",
    "PPh23",
    "PPh23",
    "PPh23",
    "PPh23",
    "PPh23",
    "PPh23",
    "PPh23",
    "PPh23",
    "PPh23",
    "PPh23",
    "PPh23",
    "PPh23",
    "PPh23",
    "PPh23",
    "PPh23",
    "PPh23",
    "PPh23",
    "PPh23",
    "PPh23",
    "PPh23",
    "PPh23",
    "PPh23",
    "PPh23",
    "PPh23",
    "PPh23",
    "PPh23",
    "PPh23",
    "PPh23",
    "PPh23",
    "PPh23",
    "PPh23",
    "PPh23",
    "PPh23",
    "PPh23",
    "PPh23",
    "PPh23",
    "PPh23",
    "PPh23",
    "PPh23",
    "PPh23",
    "PPh23",
    "PPh23",
    "PPh23",
    "PPh23",
    "PPh23",
    "PPh23",
    "PPh23",
    "PPh23",
    "PPh23",
    "PPh23",
    "PPh23",
    "PPh23",
    "PPh23",
    "PPh23",
    "PPh23",
    "PPh23",
    "PPh23",
    "PPh23",
    "PPh23",
    "PPh23",
    "PPh23",
    "PPh23",
    "PPh23",
    "PPh23",
    "PPh23",
    "PPh23",
    "PPh23",
    "PPh23",
    "PPh26",
    "PPh26",
    "PPh26",
    "PPh26",
    "PPh26",
    "PPh26",
    "PPh26",
    "PPh26",
    "PPh26",
    "PPh26",
    "PPh26",
    "PPh26",
    "PPh26",
    "PPh4(2)",
    "PPh4(2)",
    "PPh4(2)",
    "PPh4(2)",
    "PPh4(2)",
    "PPh4(2)",
    "PPh4(2)",
    "PPh4(2)",
    "PPh4(2)",
    "PPh4(2)",
    "PPh4(2)",
    "PPh4(2)",
    "PPh4(2)",
    "PPh4(2)",
    "PPh4(2)",
    "PPh4(2)",
    "PPh4(2)",
    "PPh4(2)",
    "PPh4(2)",
    "PPh4(2)",
    "PPh4(2)",
    "PPh4(2)",
    "PPh4(2)",
    "PPh15",
    "PPh15",
    "PPh15",
    "PPh15",
    "PPh15",
    "PPh15",
    "PPh15",
    "PPh22",
    "PPh22",
    "PPh22",
    "PPh22",
    "PPh22",
    "PPh22",
    "PPh22",
    "PPh22",
    "PPh22",
    "PPh22",
    "PPh22",
    "PPh22",
    "PPh22",
    "PPh22",
    "PPh22",
    "PPh22",
    "PPh22",
    "PPh22",
    "PPh22"
  ];

  List _kapkjs = [
    "411124/101",
    "411124/102",
    "411124/103",
    "411124/100",
    "411124/100",
    "411124/104",
    "411124/104",
    "411124/104",
    "411124/104",
    "411124/104",
    "411124/104",
    "411124/104",
    "411124/104",
    "411124/104",
    "411124/104",
    "411124/104",
    "411124/104",
    "411124/104",
    "411124/104",
    "411124/104",
    "411124/104",
    "411124/104",
    "411124/104",
    "411124/104",
    "411124/104",
    "411124/104",
    "411124/104",
    "411124/104",
    "411124/104",
    "411124/104",
    "411124/104",
    "411124/104",
    "411124/104",
    "411124/104",
    "411124/104",
    "411124/104",
    "411124/104",
    "411124/104",
    "411124/104",
    "411124/104",
    "411124/104",
    "411124/104",
    "411124/104",
    "411124/104",
    "411124/104",
    "411124/104",
    "411124/104",
    "411124/104",
    "411124/104",
    "411124/104",
    "411124/104",
    "411124/104",
    "411124/104",
    "411124/104",
    "411124/104",
    "411124/104",
    "411124/104",
    "411124/104",
    "411124/104",
    "411124/104",
    "411124/104",
    "411124/104",
    "411124/104",
    "411124/104",
    "411124/104",
    "411124/104",
    "411124/104",
    "411124/104",
    "411124/104",
    "411124/104",
    "411127/101",
    "411127/102",
    "411127/103",
    "411127/100",
    "411127/104",
    "411127/100",
    "411127/100",
    "411127/102",
    "411127/100",
    "411127/100",
    "411127/100",
    "411127/100",
    "411127/105",
    "411128/404",
    "411128/404",
    "411128/404",
    "411128/404",
    "411128/407",
    "411128/406",
    "411128/401",
    "411128/401",
    "411128/405",
    "411128/403",
    "411128/409",
    "411128/409",
    "411128/409",
    "411128/409",
    "411128/409",
    "411128/409",
    "411128/409",
    "411128/402",
    "411128/402",
    "411128/402",
    "411128/417",
    "411128/419",
    "411128/423",
    "411128/410",
    "411128/410",
    "411128/411",
    "411128/411",
    "411129/101",
    "411128/413",
    "411128/415",
    "411122/100",
    "411122/100",
    "411122/100",
    "411122/100",
    "411122/100",
    "411122/100",
    "411122/403",
    "411122/403",
    "411122/403",
    "411122/403",
    "411122/403",
    "411122/100",
    "411122/100",
    "411122/100",
    "411122/100",
    "411122/401",
    "411122/100",
    "411122/100",
    "411122/100"
  ];

  List _tarifBerNPWP = [
    "15%",
    "15%",
    "15%",
    "15%",
    "2%",
    "2%",
    "2%",
    "2%",
    "2%",
    "2%",
    "2%",
    "2%",
    "2%",
    "2%",
    "2%",
    "2%",
    "2%",
    "2%",
    "2%",
    "2%",
    "2%",
    "2%",
    "2%",
    "2%",
    "2%",
    "2%",
    "2%",
    "2%",
    "2%",
    "2%",
    "2%",
    "2%",
    "2%",
    "2%",
    "2%",
    "2%",
    "2%",
    "2%",
    "2%",
    "2%",
    "2%",
    "2%",
    "2%",
    "2%",
    "2%",
    "2%",
    "2%",
    "2%",
    "2%",
    "2%",
    "2%",
    "2%",
    "2%",
    "2%",
    "2%",
    "2%",
    "2%",
    "2%",
    "2%",
    "2%",
    "2%",
    "2%",
    "2%",
    "2%",
    "2%",
    "2%",
    "2%",
    "2%",
    "2%",
    "2%",
    "20%",
    "20%",
    "20%",
    "20%",
    "20%",
    "20%",
    "20%",
    "20%",
    "20%",
    "20%",
    "20%",
    "20%",
    "20%",
    "20%",
    "20%",
    "20%",
    "20%",
    "0.5%",
    "0.1%",
    "15%",
    "20%",
    "25%",
    "10%",
    "4%",
    "6%",
    "2%",
    "3%",
    "4%",
    "4%",
    "6%",
    "2.5%",
    "1%",
    "0%",
    "10%",
    "10%",
    "0.5%",
    "1.20%",
    "1.20%",
    "2.64%",
    "2.64%",
    "1.80%",
    "0.44%",
    "5%",
    "0.25%",
    "0.10%",
    "0.30%",
    "0.45%",
    "0.30%",
    "0.25%",
    "1.00%",
    "5.00%",
    "5.00%",
    "5.00%",
    "5.00%",
    "1.50%",
    "2.50%",
    "7.50%",
    "7.50%",
    "0.25%",
    "0.30%",
    "0.30%",
    "0.30%"
  ];

  List _tarifTidakBerNPWP = [
    "30%",
    "30%",
    "30%",
    "30%",
    "4%",
    "4%",
    "4%",
    "4%",
    "4%",
    "4%",
    "4%",
    "4%",
    "4%",
    "4%",
    "4%",
    "4%",
    "4%",
    "4%",
    "4%",
    "4%",
    "4%",
    "4%",
    "4%",
    "4%",
    "4%",
    "4%",
    "4%",
    "4%",
    "4%",
    "4%",
    "4%",
    "4%",
    "4%",
    "4%",
    "4%",
    "4%",
    "4%",
    "4%",
    "4%",
    "4%",
    "4%",
    "4%",
    "4%",
    "4%",
    "4%",
    "4%",
    "4%",
    "4%",
    "4%",
    "4%",
    "4%",
    "4%",
    "4%",
    "4%",
    "4%",
    "4%",
    "4%",
    "4%",
    "4%",
    "4%",
    "4%",
    "4%",
    "4%",
    "4%",
    "4%",
    "4%",
    "4%",
    "4%",
    "4%",
    "4%",
    "atau tarif P3B",
    "atau tarif P3B",
    "atau tarif P3B",
    "atau tarif P3B",
    "atau tarif P3B",
    "atau tarif P3B",
    "atau tarif P3B",
    "atau tarif P3B",
    "atau tarif P3B",
    "atau tarif P3B",
    "atau tarif P3B",
    "atau tarif P3B",
    "atau tarif P3B",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "0.50%",
    "0.20%",
    "0.60%",
    "0.90%",
    "0.60%",
    "0.50%",
    "2.00%",
    "10.00%",
    "10.00%",
    "10.00%",
    "10.00%",
    "3.00%",
    "5.00%",
    "15.00%",
    "15.00%",
    "0.25%",
    "0.60%",
    "0.60%",
    "0.60%"
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Tax Tools"),
        backgroundColor: Colors.red[800],
      ),
      body: Card(
        child: Column(
          children: [
            Container(
              child: Padding(
                padding: const EdgeInsets.all(8.0),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      "WHT 23/26 List:",
                      textAlign: TextAlign.left,
                      style:
                          TextStyle(fontWeight: FontWeight.bold, fontSize: 14),
                    ),
                    DropdownButtonHideUnderline(
                      child: SearchableDropdown.single(
                        items: _uraian.map((value) {
                          return DropdownMenuItem(
                            child: Text(value),
                            value: value,
                          );
                        }).toList(),
                        value: _valJasa,
                        hint: "Pilih Jenis Jasa",
                        searchHint: "Pilih Jenis Jasa",
                        onChanged: (value) {
                          int index = _uraian.indexOf(value);
                          setState(() {
                            _valJasa = value;
                            _valJenisPPH = _jenisPPH[index];
                            _valKapKjs = _kapkjs[index];
                            _valTarifBerNPWP = _tarifBerNPWP[index];
                            _valTarifTidakBerNPWP = _tarifTidakBerNPWP[index];
                          });
                        },
                        closeButton: null,
                        isExpanded: true,
                        dialogBox: true,
                        style: Theme.of(context).textTheme.caption,
                      ),
                    ),
                  ],
                ),
              ),
            ),
            Divider(color: Colors.black),
            _valJasa != null
                ? Container(
                    child: Padding(
                      padding: const EdgeInsets.all(8.0),
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text(
                            "Tarif:",
                            textAlign: TextAlign.left,
                            style: TextStyle(
                                fontWeight: FontWeight.bold, fontSize: 14),
                          ),
                          Table(
                              border: TableBorder.all(
                                  color: Colors.black26,
                                  width: 1,
                                  style: BorderStyle.none),
                              children: [
                                TableRow(children: [
                                  TableCell(child: Text('Jenis PPH')),
                                  TableCell(
                                      child: Text(
                                    _valJenisPPH,
                                    textAlign: TextAlign.right,
                                  )),
                                ]),
                                TableRow(children: [
                                  TableCell(child: Text('KAP / KJS')),
                                  TableCell(
                                      child: Text(
                                    _valKapKjs,
                                    textAlign: TextAlign.right,
                                  )),
                                ]),
                                TableRow(children: [
                                  TableCell(child: Text('Tarif ber-NPWP')),
                                  TableCell(
                                      child: Text(
                                    _valTarifBerNPWP,
                                    textAlign: TextAlign.right,
                                  )),
                                ]),
                                TableRow(children: [
                                  TableCell(
                                      child: Text('Tarif tidak ber-NPWP')),
                                  TableCell(
                                      child: Text(
                                    _valTarifTidakBerNPWP,
                                    textAlign: TextAlign.right,
                                  )),
                                ]),
                              ])
                        ],
                      ),
                    ),
                  )
                : SizedBox()
          ],
        ),
      ),
    );
  }
}
